(function(){
const KEY='orchardPWA_v2_state', C={planted:'#2f7d37',pending:'#eb9119',purchase:'#cd2d2d',blue:'#357ab8',purple:'#7a4aa0'};
const master=window.MASTER; let data,sel=null,layer='current',labels=true,history=[],future=[],nextId=100,dfN=1;
let zoom=1,panX=0,panY=0,pointers=new Map(),lastDist=0,lastMid=null,dragId=null,dragStart=null;
const $=id=>document.getElementById(id), svg=$('yard'), vp=$('viewport'), cp=$('canopies'), pp=$('plants');
const fields={nm:$('nm'),cat:$('cat'),lock:$('lock'),xx:$('xx'),yy:$('yy'),cc:$('cc'),c1:$('c1'),c2:$('c2'),c3:$('c3'),notes:$('notes')};
function clone(x){return JSON.parse(JSON.stringify(x))} function load(){try{data=JSON.parse(localStorage.getItem(KEY))||clone(master)}catch(e){data=clone(master)}} 
function save(){try{localStorage.setItem(KEY,JSON.stringify(data));$('saved').textContent='Saved ✓'}catch(e){$('saved').textContent='Backup recommended'}}
function snap(){history.push(JSON.stringify(data));if(history.length>40)history.shift();future=[]}
function clear(n){while(n.firstChild)n.removeChild(n.firstChild)} function S(t,a){let n=document.createElementNS('http://www.w3.org/2000/svg',t);Object.keys(a).forEach(k=>n.setAttribute(k,a[k]));return n}
function render(){clear(cp);clear(pp);data.forEach(p=>{let col=C[p.cat]||C.blue,d=Math.max(.5,Number(p.canopy[layer])||1);cp.appendChild(S('circle',{cx:p.x,cy:p.y,r:d/2,fill:col,stroke:col,class:'canopy'}));let g=S('g',{'data-id':p.id,class:'plant '+(sel===p.id?'sel':'')});g.appendChild(S('circle',{cx:p.x,cy:p.y,r:.55,fill:col,class:'marker'}));if(labels){let t=S('text',{x:p.x+.7,y:p.y-.55,class:'lbl'});t.textContent=p.name;g.appendChild(t)}pp.appendChild(g)}); renderList()}
function renderList(){clear($('list'));data.forEach(p=>{let b=document.createElement('button');b.textContent=p.name;b.onclick=()=>select(p.id);$('list').appendChild(b)})}
function select(id){sel=id;let p=data.find(x=>x.id===id);if(!p)return;$('editor').classList.remove('collapsed');$('head').textContent=p.name+' ▴';Object.values(fields).forEach(x=>x.disabled=false);$('dup').disabled=$('del').disabled=false;fields.nm.value=p.name;fields.cat.value=p.cat;fields.lock.value=p.locked?'yes':'no';fields.xx.value=p.x;fields.yy.value=p.y;fields.cc.value=p.canopy.current;fields.c1.value=p.canopy.y1;fields.c2.value=p.canopy.y2;fields.c3.value=p.canopy.y3;fields.notes.value=p.notes||'';render()}
function edit(){let p=data.find(x=>x.id===sel);if(!p)return;snap();p.name=fields.nm.value||'Unnamed Plant';p.cat=fields.cat.value;p.locked=fields.lock.value==='yes';p.x=Math.max(0,Math.min(56,Math.round(+fields.xx.value||0)));p.y=Math.max(0,Math.min(42,Math.round(+fields.yy.value||0)));['cc','c1','c2','c3'].forEach((k,i)=>{let kk=['current','y1','y2','y3'][i];p.canopy[kk]=Math.max(.5,Math.min(50,+fields[k].value||1))});p.notes=fields.notes.value;save();render()}
Object.values(fields).forEach(x=>x.addEventListener('change',edit));
$('head').onclick=()=>$('editor').classList.toggle('collapsed');
document.querySelectorAll('[data-layer]').forEach(b=>b.onclick=()=>{layer=b.dataset.layer;document.querySelectorAll('[data-layer]').forEach(x=>x.classList.toggle('on',x===b));render()});
$('labels').onclick=function(){labels=!labels;this.classList.toggle('on',labels);render()};$('gridBtn').onclick=function(){let g=$('grid');g.style.display=g.style.display==='none'?'':'none';this.classList.toggle('on',g.style.display!=='none')};
function addPlant(name,x,y,cat='pending',sizes={current:3,y1:5,y2:7,y3:9}){snap();let p={id:nextId++,name,x,y,cat,canopy:sizes,locked:false,notes:''};data.push(p);save();select(p.id)}
$('add').onclick=()=>addPlant('New Plant',28,21);$('df').onclick=()=>{if(dfN>5){$('saved').textContent='5 DF trellises added';return}addPlant('Dragon Fruit Trellis '+dfN++,5,10,'blue',{current:4,y1:5,y2:5,y3:5})};
$('dup').onclick=()=>{let p=data.find(x=>x.id===sel);if(p)addPlant(p.name+' Copy',Math.min(56,p.x+1),Math.min(42,p.y+1),p.cat,clone(p.canopy))};
$('del').onclick=()=>{if(sel==null)return;snap();data=data.filter(x=>x.id!==sel);sel=null;save();render();$('editor').classList.add('collapsed')};
$('reset').onclick=()=>{if(confirm('Reset all plants to the master layout?')){snap();data=clone(master);save();render()}};
$('undo').onclick=()=>{if(!history.length)return;future.push(JSON.stringify(data));data=JSON.parse(history.pop());save();render()};$('redo').onclick=()=>{if(!future.length)return;history.push(JSON.stringify(data));data=JSON.parse(future.pop());save();render()};
$('export').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='backyard-orchard-backup.json';a.click();URL.revokeObjectURL(a.href)};
function transform(){svg.style.transform=`translate(${panX}px,${panY}px) scale(${zoom})`;$('fit').textContent=Math.round(zoom*100)+'%'}
function setZoom(z,cx=vp.clientWidth/2,cy=vp.clientHeight/2){let nz=Math.max(1,Math.min(4,z));let ratio=nz/zoom;panX=cx-(cx-panX)*ratio;panY=cy-(cy-panY)*ratio;zoom=nz;if(zoom===1){panX=panY=0}transform()}
$('plus').onclick=()=>setZoom(zoom*1.25);$('minus').onclick=()=>setZoom(zoom/1.25);$('fit').onclick=()=>{zoom=1;panX=panY=0;transform()};
function mapPoint(e){let r=svg.getBoundingClientRect(),v=svg.viewBox.baseVal;return{x:v.x+(e.clientX-r.left)*v.width/r.width,y:v.y+(e.clientY-r.top)*v.height/r.height}}
vp.addEventListener('pointerdown',e=>{vp.setPointerCapture?.(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});let target=e.target.closest?.('.plant');if(target&&pointers.size===1){let id=+target.dataset.id,p=data.find(x=>x.id===id);select(id);if(!p.locked){snap();dragId=id;dragStart=mapPoint(e)}}if(pointers.size===2){dragId=null;let a=[...pointers.values()];lastDist=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);lastMid={x:(a[0].x+a[1].x)/2,y:(a[0].y+a[1].y)/2}}});
vp.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){e.preventDefault();let a=[...pointers.values()],d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),m={x:(a[0].x+a[1].x)/2,y:(a[0].y+a[1].y)/2},r=vp.getBoundingClientRect();setZoom(zoom*(d/lastDist),m.x-r.left,m.y-r.top);panX+=m.x-lastMid.x;panY+=m.y-lastMid.y;lastDist=d;lastMid=m;transform()}else if(dragId!=null){e.preventDefault();let q=mapPoint(e),p=data.find(x=>x.id===dragId);p.x=Math.max(0,Math.min(56,Math.round(q.x)));p.y=Math.max(0,Math.min(42,Math.round(q.y)));render();select(dragId)}});
function end(e){pointers.delete(e.pointerId);if(dragId!=null&&pointers.size===0){dragId=null;save()}lastDist=0;lastMid=null}vp.addEventListener('pointerup',end);vp.addEventListener('pointercancel',end);
load();render();transform();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();