(function(){
const MASTER=[
{id:1,name:'RSG 1 — Ruby Supreme Guava',x:13,y:4,cat:'pending',canopy:{current:4,y1:8,y2:10,y3:12},locked:false,notes:''},
{id:2,name:'Blueberry',x:24,y:4,cat:'pending',canopy:{current:3,y1:4,y2:5,y3:5},locked:false,notes:''},
{id:3,name:'Passion Fruit',x:31,y:4,cat:'pending',canopy:{current:3,y1:6,y2:8,y3:10},locked:false,notes:''},
{id:4,name:'RSG 2 — Ruby Supreme Guava',x:40,y:4,cat:'pending',canopy:{current:4,y1:8,y2:10,y3:12},locked:false,notes:''},
{id:5,name:'Mamey',x:49,y:5,cat:'pending',canopy:{current:4,y1:8,y2:12,y3:16},locked:false,notes:''},
{id:6,name:'Sweet Tart Mango',x:13,y:10,cat:'planted',canopy:{current:6,y1:9,y2:11,y3:12},locked:false,notes:''},
{id:7,name:'Haden Mango',x:32,y:11,cat:'planted',canopy:{current:20,y1:18,y2:16,y3:15},locked:false,notes:''},
{id:8,name:'White Sapote',x:45,y:15,cat:'purchase',canopy:{current:3,y1:7,y2:11,y3:15},locked:false,notes:''},
{id:9,name:'Mango Stump / Top-work',x:6,y:19,cat:'planted',canopy:{current:2,y1:5,y2:8,y3:11},locked:false,notes:''},
{id:10,name:'Papaya',x:18,y:18,cat:'planted',canopy:{current:4,y1:5,y2:6,y3:7},locked:false,notes:''},
{id:11,name:'PPC Atemoya',x:27,y:17,cat:'purchase',canopy:{current:3,y1:6,y2:9,y3:12},locked:false,notes:''},
{id:12,name:'Geffner Atemoya',x:12,y:22,cat:'pending',canopy:{current:8,y1:9,y2:10,y3:11},locked:false,notes:''},
{id:13,name:'Cherilata',x:22,y:25,cat:'planted',canopy:{current:8,y1:10,y2:11,y3:12},locked:false,notes:''},
{id:14,name:'Coconut Cream Mango',x:10,y:30,cat:'planted',canopy:{current:5,y1:8,y2:10,y3:12},locked:false,notes:''},
{id:15,name:'Existing Mango Tree',x:47,y:25,cat:'planted',canopy:{current:12,y1:12,y2:12,y3:12},locked:false,notes:''}
];
const KEY='orchardPWA-v1',colors={planted:'#2f7d37',pending:'#eb9119',purchase:'#cd2d2d',blue:'#357ab8',purple:'#7a4aa0'},NS='http://www.w3.org/2000/svg';let data=[],selected=null,drag=null,layer='current',labelsOn=true,nextId=100,df=1,undo=[],redo=[];
const $=id=>document.getElementById(id),svg=$('yard'),cp=$('canopies'),pp=$('plants');const f={nm:$('nm'),cat:$('cat'),lock:$('lock'),xx:$('xx'),yy:$('yy'),cc:$('cc'),c1:$('c1'),c2:$('c2'),c3:$('c3'),notes:$('notes')};
const clone=x=>JSON.parse(JSON.stringify(x));function clear(n){while(n.firstChild)n.removeChild(n.firstChild)}function S(t,a){const n=document.createElementNS(NS,t);Object.keys(a).forEach(k=>n.setAttribute(k,a[k]));return n}
function load(){try{data=JSON.parse(localStorage.getItem(KEY))||clone(MASTER)}catch(e){data=clone(MASTER)}data.forEach(p=>nextId=Math.max(nextId,p.id+1))}function save(){try{localStorage.setItem(KEY,JSON.stringify(data));$('saved').textContent='Saved ✓'}catch(e){$('saved').textContent='Export backup recommended'}}function snap(){undo.push(JSON.stringify(data));if(undo.length>30)undo.shift();redo=[]}
function render(){clear(cp);clear(pp);data.forEach(p=>{let col=colors[p.cat]||colors.blue,c=S('circle',{cx:p.x,cy:p.y,r:(Number(p.canopy[layer])||1)/2,fill:col,stroke:col,class:'canopy'});cp.appendChild(c);let g=S('g',{'data-id':p.id,class:'plant '+(selected===p.id?'selected':'')}),m=S('circle',{cx:p.x,cy:p.y,r:.55,fill:col,class:'marker'});g.appendChild(m);if(labelsOn){let t=S('text',{x:p.x+.7,y:p.y-.55,class:'label'});t.textContent=p.name;g.appendChild(t)}g.addEventListener('pointerdown',start);g.addEventListener('click',choose);pp.appendChild(g)});list()}
function list(){let b=$('plantList');clear(b);data.forEach(p=>{let x=document.createElement('button');x.textContent=p.name;x.onclick=()=>{selected=p.id;show();render()};b.appendChild(x)})}
function choose(e){selected=+e.currentTarget.dataset.id;show();render()}function start(e){let p=data.find(x=>x.id===+e.currentTarget.dataset.id);selected=p.id;show();render();if(p.locked)return;snap();drag=p.id;try{svg.setPointerCapture(e.pointerId)}catch(_){}}
function point(e){let r=svg.getBoundingClientRect(),v=svg.viewBox.baseVal;return{x:v.x+(e.clientX-r.left)*v.width/r.width,y:v.y+(e.clientY-r.top)*v.height/r.height}}svg.addEventListener('pointermove',e=>{if(drag==null)return;let q=point(e),p=data.find(x=>x.id===drag);p.x=Math.max(0,Math.min(56,Math.round(q.x)));p.y=Math.max(0,Math.min(42,Math.round(q.y)));render();show()});window.addEventListener('pointerup',()=>{if(drag!=null){drag=null;save()}});
function show(){let p=data.find(x=>x.id===selected);if(!p)return;$('head').textContent=p.name;Object.values(f).forEach(x=>x.disabled=false);$('dup').disabled=$('del').disabled=false;f.nm.value=p.name;f.cat.value=p.cat;f.lock.value=p.locked?'yes':'no';f.xx.value=p.x;f.yy.value=p.y;f.cc.value=p.canopy.current;f.c1.value=p.canopy.y1;f.c2.value=p.canopy.y2;f.c3.value=p.canopy.y3;f.notes.value=p.notes||''}
function edit(){let p=data.find(x=>x.id===selected);if(!p)return;snap();p.name=f.nm.value.trim()||'Unnamed Plant';p.cat=f.cat.value;p.locked=f.lock.value==='yes';p.x=Math.max(0,Math.min(56,Math.round(+f.xx.value||0)));p.y=Math.max(0,Math.min(42,Math.round(+f.yy.value||0)));p.canopy={current:Math.max(.5,+f.cc.value||1),y1:Math.max(.5,+f.c1.value||1),y2:Math.max(.5,+f.c2.value||1),y3:Math.max(.5,+f.c3.value||1)};p.notes=f.notes.value;save();render();show()}Object.values(f).forEach(x=>x.addEventListener('change',edit));
document.querySelectorAll('.layer').forEach(b=>b.onclick=()=>{layer=b.dataset.layer;document.querySelectorAll('.layer').forEach(x=>x.classList.toggle('on',x===b));render()});$('labels').onclick=function(){labelsOn=!labelsOn;this.classList.toggle('on',labelsOn);render()};$('gridBtn').onclick=function(){let g=$('grid'),on=g.style.display!=='none';g.style.display=on?'none':'';this.classList.toggle('on',!on)};
function add(name,x,y,cat='pending'){snap();let p={id:nextId++,name,x,y,cat,canopy:{current:3,y1:5,y2:7,y3:9},locked:false,notes:''};data.push(p);selected=p.id;save();render();show()}$('add').onclick=()=>add('New Plant',28,21);$('df').onclick=()=>{add('Dragon Fruit Trellis '+df++,5,10,'blue')};$('dup').onclick=()=>{let p=data.find(x=>x.id===selected);if(p){snap();let q=clone(p);q.id=nextId++;q.name+=' Copy';q.x=Math.min(56,q.x+1);q.y=Math.min(42,q.y+1);data.push(q);selected=q.id;save();render();show()}};$('del').onclick=()=>{if(selected==null)return;snap();data=data.filter(x=>x.id!==selected);selected=null;save();render();$('head').textContent='Select a plant'};
$('undo').onclick=()=>{if(!undo.length)return;redo.push(JSON.stringify(data));data=JSON.parse(undo.pop());save();render()};$('redo').onclick=()=>{if(!redo.length)return;undo.push(JSON.stringify(data));data=JSON.parse(redo.pop());save();render()};$('reset').onclick=()=>{if(confirm('Reset to the master orchard layout?')){snap();data=clone(MASTER);selected=null;save();render()}};
$('export').onclick=()=>{let blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='backyard-orchard-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};$('importBtn').onclick=()=>$('importFile').click();$('importFile').onchange=e=>{let file=e.target.files[0];if(!file)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!Array.isArray(x))throw 0;snap();data=x;save();render()}catch(_){alert('That backup file could not be read.')}};r.readAsText(file)};
let ax=$('axis');for(let x=5;x<56;x+=5){let t=S('text',{x:x,y:-.3,'text-anchor':'middle'});t.textContent=x;ax.appendChild(t)}for(let y=5;y<42;y+=5){let t=S('text',{x:-.35,y:y+.2,'text-anchor':'end'});t.textContent=y;ax.appendChild(t)}load();render();if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
})();
